---
configure_dotfiles: no
configure_osx: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - shopify/shopify
  - ArmMbed/homebrew-formulae

homebrew_installed_packages:
  - brew-cask-completion
  - go
  - { name: node, install_options: '--without-npm' }
  - pyenv
  - pyenv-virtualenv
  - ccls
  - yarn
  - ag
  - tree
  - opam
  - vim
  - exa
  - zsh
  - zsh-completions
  - getantibody/tap/antibody
  - { name: r, install_options: '--with-x11' }
  - eddieantonio/eddieantonio/imgcat
  - libgit2
  - ffmpeg
  - themekit
  - geckodriver
  - pandoc
  - gpg
  - mas
  - ispell
  - arm-none-eabi-gcc

homebrew_cask_apps:
  # sudo required
  - virtualbox
  - adoptopenjdk8
  # fonts
  - font-source-code-pro
  - font-montserrat
  - font-roboto
  - font-roboto-mono
  - font-roboto-condensed
  - font-ionicons
  - font-ia-writer-duospace
  - font-encodesans
  - font-encodesans-semiexpanded
  - font-encodesans-semicondensed
  - font-encodesans-expanded
  - font-encodesans-condensed
  # core apps
  - alfred
  - { name: dropbox, install_options: '--no-quarantine' }
  - vlc
  - fantastical
  - google-chrome
  - firefox
  - skype
  - 1password
  - rectangle
  - tunnelblick
  - flux
  - hammerspoon
  - devonthink
  - slack
  - the-unarchiver
  - bartender
  - appcleaner
  - macs-fans-control
  - transmission
  - veracrypt
  - steam
  - icloud-control
  - calibre
  - jdownloader
  - musicbrainz-picard
  - quik
  - imageoptim
  - parallels
  - printopia
  - vuescan
  - handbrake
  # dev
  - emacs
  - docker
  - android-studio
  - iterm2
  - dash
  - coolterm
  - genymotion
  - rstudio
  - mactex

npm_packages:
  - prettier
  - tern
  - eslint
  - react-native-cli
  - bs-platform
  - reason-cli@latest-macos
  - typescript
  - tslint
  - javascript-typescript-langserver

# pip_packages:
#   - awscli

 mas_installed_apps:
   - { id: 1055511498, name: "Day One" }
#   - { id: 775737590, name: "iA Writer" }
   - { id: 497799835, name: "XCode" }
#   - { id: 641027709, name: "Color Picker" }
   - { id: 1435957248, name: "Drafts" }
   - { id: 1225570693, name: "Ulysses" }
   - { id: 904280696, name: "Things 3" }
#   - { id: 451691288, name: "Contacts Sync for Google Gmail" }

gem_packages:
  - cocoapods
