---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Podcasts
- 'App Store'
- Calendar
- Mail
- Contacts
- Pages
- Keynote
- Numbers
- Photos
- iMovie
dockitems_persist:
- name: Superhuman
  path: "/Applications/Superhuman.app/"
  pos: 1
- name: Fantastical
  path: "/Applications/Fantastical.app/"
  pos: 2
- name: iTerm
  path: "/Applications/iTerm.app/"
  pos: 3
- name: Slack
  path: "/Applications/Slack.app/"
  pos: 4

homebrew_taps:
  - homebrew/core
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - shopify/shopify
  - ArmMbed/homebrew-formulae

homebrew_installed_packages:
  - brew-cask-completion
  - go
  - node
  - miniconda
  - ccls
  - yarn
  - ag
  - tree
  - opam
  - vim
  - exa
  - zsh
  - zsh-completions
  - getantibody/tap/antibody
  - r
  - tcl-tk
  - libgit2
  - ffmpeg
  - themekit
  - geckodriver
  - pandoc
  - gpg
  - mas
  - ispell
  - arm-none-eabi-gcc

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # sudo required
  # - virtualbox
  - temurin8
  - xquartz
  # fonts
  - font-source-code-pro
  - font-montserrat
  - font-roboto
  - font-roboto-mono
  - font-ia-writer-duospace
  # core apps
  - alfred
  - dropbox
  - vlc
  - fantastical
  - google-chrome
  - firefox
  - skype
  - 1password
  - rectangle
  - tunnelblick
  - flux
  - hammerspoon
  - devonthink
  - slack
  - the-unarchiver
  - bartender
  - appcleaner
  - macs-fan-control
  - transmission
  - veracrypt
  - steam
  - icloud-control
  - calibre
  - jdownloader
  - musicbrainz-picard
  - imageoptim
  - vuescan
  - handbrake
  # dev
  - emacs
  - docker
  - android-studio
  - iterm2
  - dash
  - coolterm
  # - genymotion
  - rstudio
  - mactex
  # eliminate?
  # - quik
  # - parallels
  # - printopia

mas_installed_apps:
  - { id: 1055511498, name: "Day One" }
#   - { id: 775737590, name: "iA Writer" }
  - { id: 497799835, name: "XCode" }
#   - { id: 641027709, name: "Color Picker" }
  - { id: 1435957248, name: "Drafts" }
  - { id: 1225570693, name: "Ulysses" }
#  - { id: 904280696, name: "Things 3" }
  - { id: 1346190318, name: "OmniFocus" }
  - { id: 443987910, name: "1Password" }
mas_email: ""
mas_password: ""

gem_packages:
  - cocoapods

pip_packages:
  - awscli

npm_packages:
  - prettier
  - tern
  - eslint
  - react-native-cli
  - bs-platform
  - reason-cli@latest-macos
  - typescript
  - tslint
  - javascript-typescript-langserver

configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - "./tasks/other-setup.yml"
