---
configure_dotfiles: no
configure_osx: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask-versions
  - homebrew/cask-fonts

homebrew_installed_packages:
  - brew-cask-completion
  - go
  - { name: node, install_options: '--without-npm' }
  - pyenv
  - ctags
  - yarn
  - ag
  - tree
  - opam
  - vim
  - exa
  - zsh
  - zsh-completions
  - getantibody/tap/antibody
  - { name: r, install_options: '--with-x11' }
  - eddieantonio/eddieantonio/imgcat

homebrew_cask_apps:
  # sudo required
  - virtualbox
  - java8
  # fonts
  - font-source-code-pro
  - font-montserrat
  - font-roboto
  - font-roboto-mono
  - font-roboto-condensed
  - font-ionicons
  - font-ia-writer-duospace
  - font-encodesans
  - font-encodesans-semiexpanded
  - font-encodesans-semicondensed
  - font-encodesans-expanded
  - font-encodesans-condensed
  # core apps
  - alfred
  - dropbox
  - google-backup-and-sync
  - vlc
  - fantastical
  - google-chrome
  - skype
  - 1password
  - spectacle
  - omnifocus
  - tunnelblick
  - caffeine
  - flux
  # - hammerspoon
  - devonthink-pro-office
  - slack
  - the-unarchiver
  - appcleaner
  - mac-fans-control
  - disk-inventory-x
  - transmission
  - veracrypt
  - rocket
  - steam
  - icloud-control
  - calibre
  - marshallofsound-google-play-music-player
  - quik
  - parallels13
  # dev
  - emacs
  - docker
  - android-studio
  - android-sdk
  - iterm2
  - dash
  - coolterm
  - genymotion
  - livereload
  - rstudio

npm_packages:
  - prettier
  - tern
  - eslint
  - react-native-cli
  - bs-platform
  - reason-cli@latest-macos

# pip_packages:
#   - awscli

# mas_installed_apps:
#   - { id: 1055511498, name: "Day One" }
#   - { id: 775737590, name: "iA Writer" }
#   - { id: 497799835, name: "XCode" }
#   - { id: 641027709, name: "Color Picker" }

gem_packages:
  - cocoapods
