homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - doxygen
  - git
  - go
  - gpg
  - iperf
  - packer
  - python
  - openssl
  - wget
  - vim
  - neovim
  - md5sha1sum
  - tree
  - ctags
  - awscli
  - cfssl
  - tmux
  - terraform
  - python3
  - pyenv
  - readline
  - rbenv
  - ruby-build

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - skype
  - slack
  - sublime-text
  - vagrant
  - virtualbox
  - vlc
  - iterm2
  - superduper
  - flowdock
  - atom
