---
# Whether to install Rosetta on Apple Silicon Macs
install_rosetta: true

# File from which to read dock items.
# File should be in the format output by "dockutil --list"
dock_list_file: "~/.config/dock-items.tsv"

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/kdkasad/dotfiles.git
dotfiles_repo_ref: master
dotfiles_repo_local_path: ~/.config/dotfiles
dotfiles_exclude:
  - README.md
  - LICENSE
  - .gitignore

iterm2_settings_dir: "~/.config/iterm2/my-settings"

# Homebrew settings. See geerlingguy.mac.homebrew documentation.
homebrew_taps: []
homebrew_cask_appdir: /Applications
homebrew_installed_packages_file: ~/.config/setup/homebrew/packages
homebrew_cask_apps_file: ~/.config/setup/homebrew/casks

# mas_email is set using vars_prompt in main.yml
mas_signin_dialog: true
# File containing list to assign to mas_installed_apps variable.
# See geerlingguy.mac.mas role documentation for more information.
mas_installed_apps_file: "~/.config/setup/mas-apps.yml"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# File containing settings to set via defaults(1).
# Each line should contain domain, key, type, value in that order, separated by tabs.
defaults_settings_file: ~/.config/defaults
