---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
#    - name: Install Homebrew applications
#      homebrew:
#        name: "{{ homebrew_apps }}"

#    - name: Tap Homebrew casks
#      homebrew_tap:
#        name: "{{ homebrew_taps }}"

    - name: Install Homebrew cask applications
      homebrew_cask:
        name: "{{ homebrew_cask_apps }}"
