---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  vars_prompt:
    - name: mas_email
      prompt: "Enter your Apple ID email address"
      private: false

  roles:
    - name: Install MacOS command-line tools.
      role: elliotweiser.osx-command-line-tools

    - name: Install Homebrew & packages
      role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - name: Install dotfiles
      role: dotfiles
      tags: ['dotfiles']

    - name: Customize sudoers configuration
      role: sudoers

    - name: Install App Store apps
      role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

    - name: Install VSCodium extensions
      role: vscodium_extensions

  tasks:
    - name: Configure iTerm2 to load settings from filesystem
      community.general.osx_defaults:
        state: present
        domain: com.googlecode.iterm2
        key: "{{ item.0 }}"
        type: "{{ item.1 }}"
        value: "{{ item.2 }}"
      loop:
        - ['PrefsCustomFolder', 'string', '{{ iterm2_settings_dir }}']  # Set directory to load settings from
        - ['LoadPrefsFromCustomFolder', 'bool', true]  # Enable loading settings from directory
        - ['NoSyncNeverRemindPrefsChangesLostForFile_selection', 'int', 2]  # Automatically save changes to settings

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
