---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - tmh.homebrew
#    - tmh.dotfiles
#    - name: tmh.mas
#      when: mas_installed_apps

  tasks:
    - include: tasks/ansible-setup.yml

#    - include: tasks/sudoers.yml
#      when: configure_sudoers
#
#    - include: tasks/terminal.yml
#      when: configure_terminal
#
#    - include: tasks/osx.yml
#      when: configure_osx
