---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  
  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: ['osx']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew','osx']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas','osx']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock','osx']
    - role: markosamuli.nvm
      tags: ['node']
    - role: markosamuli.asdf
      tags: ['asdf']
    - role: diodonfrost.p10k
      when: configure_p10k
      tags: ['p10k']

      # TODO Install ZSH, OMZ, P10k and set up plugins and Add scripts
      # Fix issue with golang path 


  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
