---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: sculley.mac_setup.homebrew
      tags: ['homebrew']

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - role: sculley.mac_setup.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - role: sculley.mac_setup.dock
      when: configure_dock
      tags: ['dock']

    - role: sculley.mac_setup.iterm2
      when: iterm2_dynamic_profile_urls
      tags: ['iterm2']
     
    - role: sculley.mac_setup.powerlevel10k
      when: configure_powerlevel10k
      tags: ['powerlevel10k']

  tasks:
    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
