---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: sculley.mac_setup.ohmyzsh
      tags: ['ohmyzsh']

    - role: sculley.mac_setup.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - role: sculley.mac_setup.homebrew
      tags: ['homebrew']

    - role: sculley.mac_setup.mas
      when: mas_enabled
      tags: ['mas']

    - role: sculley.mac_setup.dock
      when: configure_dock
      tags: ['dock']

    - role: sculley.mac_setup.iterm2
      when: configure_iterm2
      tags: ['iterm2']

    - role: sculley.mac_setup.powerlevel10k
      when: configure_powerlevel10k
      tags: ['powerlevel10k']

    - role: sculley.mac_setup.vscode_extensions
      when: configure_vscode_extensions
      tags: ['vscode_extensions']

  tasks:
    - ansible.builtin.include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - ansible.builtin.include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      block:
        - name: Apply post provision tasks.
          ansible.builtin.include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
      tags: ['post']
