---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  tasks:
    - name: Install MacOS command-line tools.
      ansible.builtin.import_role:
        name: elliotweiser.osx-command-line-tools

    - name: Install Rosetta
      ansible.builtin.command:
        cmd: softwareupdate --install-rosetta
        stdin: A
        stdin_add_newline: yes
        creates: /usr/libexec/rosetta/oahd
      when: ansible_machine == 'arm64'

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      tags: ['dotfiles']

    - name: Install Homebrew & packages
      ansible.builtin.import_role:
        name: homebrew
      tags: ['homebrew']

    - name: Create new PATH including Homebrew packages
      ansible.builtin.set_fact:
        new_path: /opt/homebrew/bin:{{ ansible_env['PATH'] | default('') }}
      tags:
        - always

    - name: Set defaults
      ansible.builtin.import_role:
        name: defaults_settings
      when: (defaults_settings_file is defined) and defaults_settings_file

    - name: Customize sudoers configuration
      ansible.builtin.import_role:
        name: sudoers
      when: (sudoers_custom_config_file is defined) and sudoers_custom_config_file

    - name: Enable Touch ID for sudo(1)
      ansible.builtin.lineinfile:
        path: /private/etc/pam.d/sudo_local
        create: yes
        owner: root
        mode: '0644'
        line: auth sufficient pam_tid.so
        regexp: 'auth\s+sufficient\s+pam_tid\.so'
      become: yes

    - name: Install App Store apps
      ansible.builtin.import_role:
        name: mas
      environment:
        PATH: "{{ new_path }}"
      when: >-
        ((mas_installed_apps is defined) and mas_installed_apps)
        or ((mas_installed_apps_file is defined) and mas_installed_apps_file)
      tags: ['mas']

    - name: Configure dock
      ansible.builtin.import_role:
        name: dock
      when: (dock_list_file is defined) and dock_list_file
      tags: ['dock']

    - name: Configure iTerm2 to load settings from filesystem
      community.general.osx_defaults:
        state: present
        domain: com.googlecode.iterm2
        key: "{{ item.0 }}"
        type: "{{ item.1 }}"
        value: "{{ item.2 }}"
      loop:
        - ['PrefsCustomFolder', 'string', '{{ iterm2_settings_dir }}']  # Set directory to load settings from
        - ['LoadPrefsFromCustomFolder', 'bool', true]  # Enable loading settings from directory
        - ['NoSyncNeverRemindPrefsChangesLostForFile_selection', 'int', 2]  # Automatically save changes to settings

    - name: Install VSCodium extensions
      ansible.builtin.import_role:
        name: vscodium_extensions
      environment:
        PATH: "{{ new_path }}"

    - name: Install NVM & Node.js
      ansible.builtin.import_role:
        name: nvm
      environment:
        PATH: "{{ new_path }}"
      tags:
        - nvm

    - name: Build & install Iosevka font
      when: iosevka_enabled
      ansible.builtin.import_role:
        name: iosevka
      environment:
        PATH: "{{ new_path }}"
      tags:
        - iosevka
