---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles

collections:
  - name: geerlingguy.mac
  - type: git
    source: https://github.com/komailo/ansible-collection-mac-dev.git
