---
- name: Install asdf plugins.
  vars:
    asdf_init_shell: false
  asdf_plugins:
    name: "{{ item.name | default(item) }}"
    repository: "{{ item.state | default(omit) }}"
    versions: '{{ item.versions | default(''["latest"]'') }}'
    global: "{{ item.global | default('latest') }}"
  loop: "{{ asdf_plugins }}"
