---
- name: ensure dirs exis
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sublime_base_path }}/{{ sublime_config_path }}"
    - "{{ sublime_base_path }}/Installed Packages"
- name: create Sublime Text Control Package config
  ansible.builtin.template:
    src: templates/Package_Control.sublime-settings.j2
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Package Control.sublime-settings"
- name: Ensure Sublime text user Preference settings
  ansible.builtin.copy:
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Preferences.sublime-settings"
    content: "{{ sublime_preferences | to_nice_json }}"
- name: ensure Sublime Package control is downloaded
  ansible.builtin.get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_base_path }}/Installed Packages/Package Control.sublime-package"
