---
- name: Ensure Sublime Text directories exist.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sublime_base_path }}/{{ sublime_config_path }}"
    - "{{ sublime_base_path }}/Installed Packages"

- name: Ensure Sublime Package Control is installed.
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_base_path }}/Installed Packages/Package Control.sublime-package"

- name: Ensure Sublime Package Control Packages are configured.
  template:
    src: templates/Package_Control.sublime-settings.j2
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Package Control.sublime-settings"

- name: Ensure Sublime text user Preferences and theme are set.
  copy:
    src: "files/sublime/{{ item }}"
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/{{ item }}"
  loop:
    - "Cobalt (SL).tmTheme"
    - "Markdown.sublime-settings"
    - "Plain text.sublime-settings"
    - "Preferences.sublime-settings"
    - "WordCount.sublime-settings"
