---
- name: Read installed apps list
  when: >-
    (mas_installed_apps is undefined)
    and (mas_installed_apps_file is defined)
    and mas_installed_apps_file
  block:
    - name: Read file
      ansible.builtin.slurp:
        path: "{{ mas_installed_apps_file }}"
      register: slurp

    - name: Set variable with list contents
      ansible.builtin.set_fact:
        mas_installed_apps: "{{ slurp.content | b64decode | from_yaml }}"

- name: Install App Store apps
  ansible.builtin.include_role:
    name: geerlingguy.mac.mas
