---
- name: Read installed apps
  ansible.builtin.slurp:
    path: "{{ mas_installed_apps_file }}"
  register: slurp

- name: Install App Store apps
  ansible.builtin.import_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps: "{{ slurp.content | b64decode | from_yaml }}"
