---
- name: Detect if Rosetta is installed
  ansible.builtin.command:
    cmd: pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto
  changed_when: false
  register: pkginfo
  failed_when: false
  when: ansible_machine == 'arm64'

- name: Install Rosetta
  ansible.builtin.command:
    cmd: softwareupdate --install-rosetta
    stdin: A
    stdin_add_newline: yes
  when: pkginfo.rc != 0 and ansible_machine == 'arm64'
