---

- name: Determine whether the git-workspace directory exists
  ansible.builtin.stat:
    path: ~/git-workspace
  register: git_directory

- name: Create git-workspace directory
  ansible.builtin.file:
    path: ~/git-workspace
    state: directory
  when: not git_directory.stat.exists