---
- name: Create venvs directory
  ansible.builtin.file:
    path: ~/venvs
    state: directory

- name: Determine whether the ~/venvs/ansible directory exists
  ansible.builtin.stat:
    path: ~/venvs/ansible0214
  register: ansible_directory

- name: Create ansible 2.14 Virtual Environment
  command: python3 -m venv ~/venvs/ansible0214
  when: not ansible_directory.stat.exists