---
- hosts: all
  connection: local

  tasks:
    - name: Install Xcode CLI tools
      shell: /usr/bin/xcode-select --install creates=/usr/bin/gcc
      sudo: yes

    - name: Run Homebrew install script
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" creates=/usr/local/bin/brew
      register: brew_result
      sudo: yes
