---
- hosts: all
  connection: local
  vars:
    app_name: Sublime\ Text
    app_name_pretty: Sublime\ Text
    app_url: "http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203059.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Sublime\ Text/
    downloads: ~/.ansible-downloads/

  tasks:
    - include: ../install/{{ install_method }}.yml
    - name: Create symlink subl for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/subl state=link
      sudo: true
    - name: Create symlink sublime for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/sublime state=link
      sudo: true