---
- include: ../setup.yaml

- hosts: $hosts
  user: $user
  vars:
    app_name: iTerm
    app_name_pretty: iTerm
    app_url: https://copy.com/HTIIPAwoiKVY
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../install/$install_method.yaml